services:
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: better-opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: better-opensearch-dashboards
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_HOSTS='["http://opensearch:9200"]'
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.13.0
    container_name: better-jaeger
    depends_on:
      - opensearch
    command: ["--config", "/etc/jaeger/config.yaml"]
    volumes:
      - ./jaeger-config.yaml:/etc/jaeger/config.yaml:ro
      - ./jaeger-ui.json:/etc/jaeger/ui-config.json:ro
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

volumes:
  opensearch-data:
