version: 1
roles:
  - roleKey: leader
    permissions:
      - prep:waive
  - roleKey: production_supervisor
    permissions:
      - prep:waive
      - time_rule:override
  - roleKey: quality
    permissions:
      - prep:waive
      - time_rule:override

dualApproval:
  enabled: false
  rolesRequired:
    - production_supervisor
    - quality
